USE [master]
GO

/****** Object:  Database [BARADMIN]    Script Date: 26/04/2019 06:08:09 p. m. ******/
CREATE DATABASE [BARADMIN] ON  PRIMARY 
( NAME = N'BARADMIN', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\BARADMIN.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BARADMIN_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\BARADMIN_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BARADMIN] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BARADMIN].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BARADMIN] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BARADMIN] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BARADMIN] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BARADMIN] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BARADMIN] SET ARITHABORT OFF 
GO

ALTER DATABASE [BARADMIN] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BARADMIN] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BARADMIN] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BARADMIN] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BARADMIN] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BARADMIN] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BARADMIN] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BARADMIN] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BARADMIN] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BARADMIN] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BARADMIN] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BARADMIN] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BARADMIN] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BARADMIN] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BARADMIN] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BARADMIN] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BARADMIN] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BARADMIN] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BARADMIN] SET  MULTI_USER 
GO

ALTER DATABASE [BARADMIN] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BARADMIN] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BARADMIN] SET  READ_WRITE 
GO

